nav:
  - ğŸ¡ä¸»é¡µ:
    - index.md
  - è®¡ç®—æœºç³»ç»Ÿ:
    - system/index.md
  - MLSys:
    - mlsys/index.md
  - AI:
    - ai/index.md
    - Diffusion:
      - Introduction: ai/diffusion/index.md
      - "Lec1: Flow and Diffusion Models": ai/diffusion/lec1.md
      - "Lec2: Constructing a Training Target": ai/diffusion/lec2.md
      - "Lec3: Training Flow and Diffusion Models": ai/diffusion/lec3.md
      - "Lec4: Building an Image Generator": ai/diffusion/lec4.md
    - RL:
      - ai/rl/index.md
  - è®ºæ–‡é˜…è¯»:
    - papers/index.md
    - MLSys:
      - papers/blitzscale.md
      - papers/cacheblend.md
      - papers/mooncake.md
  - æ‚é¡¹:
    - misc/index.md

site_name: HarryZ ã® Notebook
site_url: https://note.uqbarz.com/
repo_url: https://github.com/hharryz/hharryz.github.io
edit_uri: raw/main/docs/
repo_name: hharryz.github.io
site_author: HarryZ
copyright: Copyright Â© HarryZ

theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme)"
      primary: slate
      toggle:
        icon: material/brightness-auto
        name: åˆ‡æ¢è‡³æµ…è‰²æ¨¡å¼
    - media: "(prefers-color-scheme: light)"
      scheme: day
      toggle:
        icon: material/brightness-7
        name: åˆ‡æ¢è‡³æ·±è‰²æ¨¡å¼
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: æ ¹æ®ç³»ç»Ÿæ¨¡å¼åˆ‡æ¢ä¸»é¢˜
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.tracking
    - navigation.path
    - navigation.top
    - toc.follow
    - content.action.view
    - search.suggest
    - search.highlight
    - search.share

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # mathjax
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.keys
  - pymdownx.critic


extra_javascript:
  # mathjax
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/polyfill/index.min.js
  - https://cdn.jsdelivr.net/npm/mathjax/es5/tex-mml-chtml.js
  # tablesort
  - javascripts/tablesort.js
  - https://cdn.jsdelivr.net/npm/tablesort/dist/tablesort.min.js

extra_css:
  - stylesheets/fonts.css
  - stylesheets/theme.css
  - stylesheets/counter.css
  - stylesheets/extra.css

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - glightbox
  - include_dir_to_nav:
      recurse: false
